-- Uniqueness of workspace names moves off `lower(name)` and onto the folded
-- column 0004 added ("Workspace names are only case-insensitive in ASCII",
-- issue 91). 0003 is the template for everything below, including its ordering
-- notes.
--
-- **The backfill under-folds, on purpose.** It uses `lower(name)` - the very
-- function this migration exists to stop trusting - because it is the only
-- fold SQL has, and the application's is not reachable from here. That is safe
-- rather than wrong: it is exact for every ASCII name, and an under-folded row
-- is too *permissive*, never falsely rejecting anything. It corrects itself the
-- next time that workspace is renamed. A workspace named before this lands and
-- never renamed keeps a slightly wrong fold forever, and that is accepted.
--
-- **Order matters.** The new index is created *before* the old one is dropped,
-- so a failure leaves the stricter guarantee standing rather than none.
--
-- **This is the statement that can fail on data.** Two live workspaces whose
-- names differ only in non-ASCII case are legal before this and illegal after.
-- They exist nowhere in seed.sql, so preview cannot hit it - but staging is
-- deliberately never seeded and has whatever has accumulated, and production is
-- a person's real data. When it happens the index is refused, this migration
-- fails, the deploy fails, and the old code keeps running against a database
-- that is otherwise untouched. That is the intended outcome, and the same one
-- 0003 chose: silently renaming somebody's workspace to get a deploy through
-- would be worse than a deploy that stops and says why. The fix is one rename
-- by hand, then redeploy.
--
-- **Every statement here is therefore re-runnable**, because that redeploy runs
-- this file again from the top. The `UPDATE` is idempotent - it only touches
-- rows the backfill has not reached - and `IF NOT EXISTS` / `IF EXISTS` are not
-- decoration: without them the retry fails on work it already did, and no
-- amount of fixing the data would get the deploy through.
--
-- **The windows this can be interrupted in**, in order:
--   1. Backfilled, before the new index exists - the old index is still the one
--      enforcing uniqueness, so nothing is weaker than before.
--   2. Both indexes present - strictly stricter than before.
--   3. After the swap, before the new code is live - old code writes no folded
--      value, so its inserts take the column default and collide with each
--      other on the empty string rather than escaping uniqueness. See 0004.
--      Stated plainly, because it cuts both ways: in that window the *second*
--      workspace old code creates is refused whatever it is called, not only
--      one whose name is taken. A deploy is seconds long and a refusal that
--      says so is recoverable; a duplicate name written past the index is not.
UPDATE `workspaces` SET `folded_name` = lower(`name`) WHERE `folded_name` = '';--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `workspaces_tenant_live_folded_name` ON `workspaces` (`tenant_id`,`folded_name`) WHERE "workspaces"."deleted_at" IS NULL;--> statement-breakpoint
DROP INDEX IF EXISTS `workspaces_tenant_live_name`;
