import { z } from 'zod';
import {
  associationKindSchema,
  dashboardNameSchema,
  itemDescriptionSchema,
  itemTitleSchema,
  prioritySchema,
  workspaceNameSchema,
} from './domain/item.js';
import { itemTypeColorSchema, itemTypeNameSchema } from './domain/item-type.js';
import { panelNameSchema, placementInputSchema } from './domain/panel.js';
import { hexColorSchema } from './domain/workspace-themes.js';

/**
 * Mutations are commands, not object PUTs (architecture, "Mutations are
 * commands, not object PUTs"). Every command carries a client-generated command
 * ID (idempotent retries) and the client timestamp (last-write-wins conflict
 * resolution).
 */
export const commandEnvelopeSchema = z.object({
  commandId: z.uuid(),
  /** Client wall-clock time when the command was issued. */
  issuedAt: z.iso.datetime(),
  workspaceId: z.string(),
});

/**
 * create_workspace — the envelope's `workspaceId` *is* the new workspace's id,
 * generated by the client like every other user-created id (architecture,
 * "Schema conventions"). That also means the change announces itself on the
 * new workspace without any special casing.
 *
 * No color: it is a function of the colors every other workspace already has,
 * and the client's copy of that list can be stale, so the server picks it.
 */
export const createWorkspaceSchema = commandEnvelopeSchema.extend({
  workspaceId: z.uuid(),
  name: workspaceNameSchema,
});
export type CreateWorkspaceCommand = z.infer<typeof createWorkspaceSchema>;

/**
 * rename_workspace — the envelope's `workspaceId` is the workspace being
 * renamed, so the change announces itself on it like every other change.
 *
 * Deliberately `workspaceNameSchema`, the same one create uses: renaming obeys
 * exactly the rules creating does, and sharing the schema is what stops the two
 * drifting apart. It trims before it measures, so the name is cleaned before
 * uniqueness is decided on it rather than after.
 *
 * Unlike create, the id here names something that already exists, and the
 * workspaces seeded before ids were client-generated are not UUIDs - so the
 * envelope's plain string is what this takes.
 */
export const renameWorkspaceSchema = commandEnvelopeSchema.extend({
  name: workspaceNameSchema,
});
export type RenameWorkspaceCommand = z.infer<typeof renameWorkspaceSchema>;

/**
 * delete_workspace — the envelope on its own: which workspace is the only
 * thing there is to say. Its items are left where they are (architecture,
 * "Schema conventions": tombstones, not deletes), because the router learns
 * from the whole history of where things were filed.
 */
export const deleteWorkspaceSchema = commandEnvelopeSchema;
export type DeleteWorkspaceCommand = z.infer<typeof deleteWorkspaceSchema>;

/**
 * reorder_workspaces — the whole order, not the move that produced it.
 *
 * **The payload is every live workspace in the order they should be in.** A
 * "move this one before that one" would be smaller, and it is the wrong unit
 * for two reasons. Commands carry the client's clock and are resolved
 * last-write-wins (architecture, "Mutations are commands, not object PUTs"), and
 * a whole order is a value that rule can be applied to while a relative move is
 * not - two moves arriving out of turn compose into an order nobody asked for.
 * And it makes the staleness visible: a list that no longer names the same
 * workspaces the account has is refused, where a relative move would quietly
 * succeed against a list the person was not looking at.
 *
 * The envelope's `workspaceId` is the one that was moved. It is not redundant
 * with the list: it is what the change announces itself on, and it is what the
 * audit trail reads as afterwards - "the whole order changed" says nothing
 * about what somebody did.
 *
 * The ids are the envelope's plain strings, not uuids, for the reason renaming
 * takes one: they name workspaces that already exist, and the ones an account
 * starts with predate client-generated ids.
 */
export const reorderWorkspacesSchema = commandEnvelopeSchema
  .extend({
    workspaceIds: z.array(z.string().min(1)).min(1),
  })
  /**
   * A list naming the same workspace twice has no order in it - two positions
   * for one workspace, and one of the account's workspaces necessarily left
   * out. Refused as a shape rather than checked against the database, because
   * it is wrong on its own terms whatever the account holds.
   */
  .refine((cmd) => new Set(cmd.workspaceIds).size === cmd.workspaceIds.length, {
    message: 'a workspace can only be in one place in the order',
    path: ['workspaceIds'],
  })
  /**
   * The workspace that moved has to be one of the workspaces being ordered.
   * Same reason: an order that does not contain the thing it claims to have
   * moved is not a smaller change, it is an inconsistent one.
   */
  .refine((cmd) => cmd.workspaceIds.includes(cmd.workspaceId), {
    message: 'the workspace that moved is not in the order',
    path: ['workspaceIds'],
  });
export type ReorderWorkspacesCommand = z.infer<typeof reorderWorkspacesSchema>;

/**
 * set_workspace_theme — the four colors, not the name of the theme they came
 * from, because four colors is what a workspace stores. The server still
 * refuses a set that is not one of the palette's, which is what keeps "picked
 * from designed options" true rather than merely intended; the day mixing your
 * own is wanted, that check relaxes and nothing else moves.
 */
export const setWorkspaceThemeSchema = commandEnvelopeSchema.extend({
  color: hexColorSchema,
  bar: hexColorSchema,
  ground: hexColorSchema,
  header: hexColorSchema,
});
export type SetWorkspaceThemeCommand = z.infer<typeof setWorkspaceThemeSchema>;

/**
 * add_dashboard — the envelope's `workspaceId` is the workspace it goes in, so
 * the change announces itself on that workspace like every other, and
 * `dashboardId` is the new dashboard's id, generated by the client like every
 * other user-created id (architecture, "Schema conventions").
 *
 * The name obeys the rules a workspace name obeys, by carrying the same
 * schema. Uniqueness is not a shape: it is decided by the handler and the index
 * behind it, in the scope of the workspace rather than the account, so two
 * workspaces may each have a Research ("Add and switch dashboards", issue 32).
 */
export const addDashboardSchema = commandEnvelopeSchema.extend({
  dashboardId: z.uuid(),
  name: dashboardNameSchema,
});
export type AddDashboardCommand = z.infer<typeof addDashboardSchema>;

/**
 * rename_dashboard — which dashboard, and what it is now called. The name obeys
 * exactly the rules adding one does, by carrying the same schema; uniqueness is
 * decided by the handler and the index behind it, in the scope of the workspace
 * ("Rename and delete a dashboard from a dashboard settings page", issue 90).
 *
 * `dashboardId` is the envelope's plain string rather than a uuid, for the
 * reason renaming a workspace takes one: it names something that already
 * exists, and the dashboard every workspace was given when dashboards landed
 * has an id derived from its workspace's, which is not a uuid.
 */
export const renameDashboardSchema = commandEnvelopeSchema.extend({
  dashboardId: z.string(),
  name: dashboardNameSchema,
});
export type RenameDashboardCommand = z.infer<typeof renameDashboardSchema>;

/**
 * delete_dashboard — which dashboard. Its panels go with it; the actions they
 * showed are keyed to the workspace and are untouched, so nothing written down
 * is lost by removing a place it was shown.
 */
export const deleteDashboardSchema = commandEnvelopeSchema.extend({
  dashboardId: z.string(),
});
export type DeleteDashboardCommand = z.infer<typeof deleteDashboardSchema>;

/**
 * add_panel — which dashboard it goes on, the new panel's id (client-generated
 * like every other user-created id), and its title.
 *
 * The title obeys the rules a dashboard's name obeys, by carrying the same
 * schema. Uniqueness is decided by the handler and the index behind it, in the
 * scope of the *dashboard* rather than the workspace, so two dashboards of one
 * workspace may each have a Reading list ("Panels on a dashboard, with
 * per-screen-size layouts", issue 33).
 *
 * Where it lands is not here. A new panel is appended to every layout the
 * dashboard has, which is the handler's job because only the store knows what
 * those layouts are - and the client's copy of them can be stale.
 */
export const addPanelSchema = commandEnvelopeSchema.extend({
  dashboardId: z.string(),
  panelId: z.uuid(),
  name: panelNameSchema,
});
export type AddPanelCommand = z.infer<typeof addPanelSchema>;

/**
 * rename_panel — which panel, and what it is now called. Every panel is created
 * by a client, so unlike a dashboard's this id really is a uuid.
 */
export const renamePanelSchema = commandEnvelopeSchema.extend({
  panelId: z.uuid(),
  name: panelNameSchema,
});
export type RenamePanelCommand = z.infer<typeof renamePanelSchema>;

/**
 * delete_panel — which panel. It leaves every layout of its dashboard with it,
 * because a layout is a list of where the panels are and one that named a panel
 * nobody can see would be a hole nothing could fill.
 */
export const deletePanelSchema = commandEnvelopeSchema.extend({
  panelId: z.uuid(),
});
export type DeletePanelCommand = z.infer<typeof deletePanelSchema>;

/**
 * save_layout — one arrangement of a dashboard's panels, whole.
 *
 * **One command for every way an arrangement changes**, rather than one per
 * gesture: dragging a panel past another, dragging its corner, and pressing
 * "Fit to this screen" all end with the same answer to the same question - here
 * is where these panels go now. Splitting them would be three commands writing
 * the same rows, and three chances for them to disagree.
 *
 * **It is an upsert, and that is what makes the issue's question answerable.**
 * A `layoutId` the dashboard already has changes that layout; a fresh one
 * defines a new layout for `screenWidth`. Those are exactly the two answers the
 * app asks for when an arrangement is changed on a screen the layout was not
 * made for, so the choice is carried by which id is sent rather than by a mode
 * flag.
 *
 * **`screenWidth` is only read when the layout is created.** A layout records
 * the width it was made at ("Panels on a dashboard, with per-screen-size
 * layouts", issue 33), so changing one from another screen must not quietly
 * move it to that screen - that is what defining a new layout is for.
 *
 * The order of `placements` is the order the panels are drawn in. Nothing else
 * carries it, which is why this is a list rather than a map.
 */
export const saveLayoutSchema = commandEnvelopeSchema.extend({
  dashboardId: z.string(),
  layoutId: z.uuid(),
  /**
   * The width of the screen this arrangement was made on, in CSS pixels.
   * Bounded so a layout can never record a width no screen has: the automatic
   * choice is "the layout whose width is closest to this screen", and one
   * absurd entry would win it everywhere or nowhere.
   */
  screenWidth: z.number().int().min(1).max(100_000),
  placements: z
    .array(placementInputSchema)
    // One entry per panel. Two entries for one panel is not an arrangement at
    // all - the panel would have two places - and the row it writes has the
    // panel in its key, so the second would silently replace the first.
    .refine((placements) => new Set(placements.map((p) => p.panelId)).size === placements.length, {
      message: 'a panel appears once in a layout',
    }),
});
export type SaveLayoutCommand = z.infer<typeof saveLayoutSchema>;

/**
 * delete_layout — which layout. The panels stay exactly where they are; what
 * goes is one way of arranging them, and the dashboard falls back to the
 * closest remaining layout ("Panels on a dashboard, with per-screen-size
 * layouts", issue 33) or, with none left, to an arrangement made for the screen
 * it is being drawn on.
 */
export const deleteLayoutSchema = commandEnvelopeSchema.extend({
  layoutId: z.uuid(),
});
export type DeleteLayoutCommand = z.infer<typeof deleteLayoutSchema>;

/**
 * capture_item — the one command with many front doors (architecture,
 * "Multi-channel capture and the task-creator merge").
 */
export const captureItemSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  /**
   * What was said, which is the Item's captured message and the only text
   * capture writes. The title is left empty and the row falls through to this
   * (`itemLabel`), so nothing has to guess a name for a thought at the moment
   * of having it. What capture *should* write into the three texts - a cleaned
   * title, several suggestions to pick from - is its own piece of work
   * (docs/ideas.md, "Capture and the task creator").
   */
  message: z.string().trim().min(1),
  nextAction: z.string().optional(),
  /**
   * What kind of thing it is ("Capture a thought or an action, and see which it
   * is", issue 155). Optional, because a capture from a front door that has no
   * picker - a dictated note, a connector - still has to land.
   *
   * The envelope's plain string rather than a uuid: it names a type that
   * already exists, and the two every account starts with have ids derived from
   * the account's own.
   */
  typeId: z.string().min(1).optional(),
});
export type CaptureItemCommand = z.infer<typeof captureItemSchema>;

/**
 * A new Type, made by naming one that is not there yet ("Capture a thought or
 * an action, and see which it is", issue 155).
 *
 * It carries no colour: which one is free is a fact about the account rather
 * than about the request, so the store decides it. That is also what makes a
 * replay harmless - the same command twice cannot be two colours.
 */
export const createItemTypeSchema = commandEnvelopeSchema.extend({
  typeId: z.uuid(),
  name: itemTypeNameSchema,
});
export type CreateItemTypeCommand = z.infer<typeof createItemTypeSchema>;

/**
 * The three changes the types page makes to one Type ("Manage the types, and
 * put them in the order you want", issue 156).
 *
 * `typeId` is the envelope's plain string rather than a uuid, for the reason
 * renaming a workspace takes one: it names something that already exists, and
 * the two every account starts with have ids derived from the account's own.
 *
 * Renaming obeys exactly the rules creating does, by carrying the same schema.
 * Uniqueness is not a shape: the handler and the index behind it decide it, in
 * the scope of the account.
 */
export const renameItemTypeSchema = commandEnvelopeSchema.extend({
  typeId: z.string().min(1),
  name: itemTypeNameSchema,
});
export type RenameItemTypeCommand = z.infer<typeof renameItemTypeSchema>;

export const setItemTypeColorSchema = commandEnvelopeSchema.extend({
  typeId: z.string().min(1),
  color: itemTypeColorSchema,
});
export type SetItemTypeColorCommand = z.infer<typeof setItemTypeColorSchema>;

/**
 * delete_item_type - which Type. Its Items are left where they are and simply
 * stop having a type, the way deleting a Workspace leaves its Items filed
 * against it: nothing written down is lost by removing a label.
 */
export const deleteItemTypeSchema = commandEnvelopeSchema.extend({
  typeId: z.string().min(1),
});
export type DeleteItemTypeCommand = z.infer<typeof deleteItemTypeSchema>;

/**
 * reorder_item_types - the whole order, not the move that produced it, for the
 * two reasons `reorder_workspaces` carries: a whole order is a value
 * last-write-wins can be applied to while a relative move is not, and a list
 * that no longer names the same types the account has is refused rather than
 * quietly succeeding against a list nobody was looking at.
 *
 * `typeId` is the one that moved, which is what the audit trail reads as
 * afterwards - "the whole order changed" says nothing about what somebody did.
 */
export const reorderItemTypesSchema = commandEnvelopeSchema
  .extend({
    typeId: z.string().min(1),
    typeIds: z.array(z.string().min(1)).min(1),
  })
  .refine((cmd) => new Set(cmd.typeIds).size === cmd.typeIds.length, {
    message: 'a type can only be in one place in the order',
    path: ['typeIds'],
  })
  .refine((cmd) => cmd.typeIds.includes(cmd.typeId), {
    message: 'the type that moved is not in the order',
    path: ['typeIds'],
  });
export type ReorderItemTypesCommand = z.infer<typeof reorderItemTypesSchema>;

/**
 * move_item_to_panel — where an Item lives now, and the order of the Panel it
 * lands on ("Panels hold the items filed into them, and the Inbox holds the
 * rest", issue 36).
 *
 * **One command for every way a Panel's contents change**, rather than one per
 * gesture: filing an Item from the Inbox, moving it between Panels, sending it
 * back to the Inbox and reordering it inside the Panel it is already on are all
 * the same answer to the same question - where do these Items go now. Splitting
 * them would be several commands writing the same rows, and several chances for
 * them to disagree. `save_layout` is the same call for the same reason.
 *
 * **A null `panelId` is the Inbox**, which is not a Panel but the absence of
 * one: the Item is taken off every Panel it was on and, being filed nowhere, is
 * in the Inbox again. Nothing has to name the Inbox for that to work.
 *
 * **`order` is the target Panel's whole order afterwards, not this Item's
 * position.** Commands carry the client's clock and are resolved
 * last-write-wins (architecture, "Mutations are commands, not object PUTs"), and
 * a whole order is a value that rule can be applied to while "put it third" is
 * not - two of those arriving out of turn compose into an order nobody asked
 * for. It is the same call `reorder_workspaces` makes, and it makes staleness
 * visible the same way: an order that no longer names the Panel's Items is
 * refused rather than quietly written.
 */
/**
 * An order names each Item once. Shared by the two commands that carry one,
 * because it is the same rule: two positions for one Item is not an order, and
 * one of the Panel's Items is necessarily left out.
 */
const namesEachItemOnce = (cmd: { order: string[] }) =>
  new Set(cmd.order).size === cmd.order.length;
const ONCE = { message: 'an item can only be in one place in the order', path: ['order'] };

export const moveItemToPanelSchema = commandEnvelopeSchema
  .extend({
    itemId: z.uuid(),
    /** The Panel it lands on, or null for the Inbox. */
    panelId: z.uuid().nullable(),
    /** Every Item on that Panel afterwards, in order. Empty for the Inbox. */
    order: z.array(z.uuid()),
  })
  /**
   * An order naming one Item twice has no order in it - two positions for one
   * Item, and one of the Panel's Items necessarily left out. Refused as a shape
   * rather than checked against the store, because it is wrong on its own terms
   * whatever the Panel holds.
   */
  .refine(namesEachItemOnce, ONCE)
  /**
   * The Item that moved has to be in the order of the Panel it moved to, and
   * has to be absent from an order for the Inbox - which has no order at all,
   * being by age. Either way an order that does not contain the thing it claims
   * to have moved is not a smaller change, it is an inconsistent one.
   */
  .refine((cmd) => (cmd.panelId === null ? cmd.order.length === 0 : cmd.order.includes(cmd.itemId)), {
    message: 'the item that moved is not in the order of the panel it moved to',
    path: ['order'],
  });
export type MoveItemToPanelCommand = z.infer<typeof moveItemToPanelSchema>;

/**
 * add_item_to_panel — the same Item on one more Panel ("Ask whether to move an
 * item to a panel or add it to one", issue 142).
 *
 * **It is `move_item_to_panel` without the taking-off.** The same Item can
 * genuinely belong on *Project Falcon* and on *Anna*, which is the whole reason
 * a Panel is a view over one shared list rather than a folder - so the only
 * difference between the two commands is whether the Panels it was already on
 * keep it.
 *
 * `order` is the target Panel's whole order afterwards, for the reason moving
 * carries one: a whole order can be resolved last-write-wins and "put it third"
 * cannot. There is no null Panel here - adding an Item to the Inbox is not a
 * thing, because the Inbox is what is filed nowhere.
 */
export const addItemToPanelSchema = commandEnvelopeSchema
  .extend({
    itemId: z.uuid(),
    panelId: z.uuid(),
    order: z.array(z.uuid()),
  })
  // The same two rules a move's order obeys, by being the same functions rather
  // than a copy of them: an order that names an item twice has no order in it,
  // and one that leaves out the item it is about is inconsistent rather than
  // smaller. There is no Inbox arm here, because there is no adding to the
  // Inbox.
  .refine(namesEachItemOnce, ONCE)
  .refine((cmd) => cmd.order.includes(cmd.itemId), {
    message: 'the item that arrived is not in the order of the panel it arrived on',
    path: ['order'],
  });
export type AddItemToPanelCommand = z.infer<typeof addItemToPanelSchema>;

/**
 * remove_item_from_panel — this Panel stops showing the Item, and every other
 * Panel holding it carries on ("Ask whether to move an item to a panel or add
 * it to one", issue 142).
 *
 * **Not a delete, and not a move.** The Item is untouched; one place it was
 * shown stops showing it. Removing it from the only Panel holding it leaves it
 * filed nowhere, which is to say back in the Inbox - so there is no separate
 * way to say "put this back for me to deal with later" needed here.
 *
 * No `order`: what is left keeps the places it had. A gap in the numbering is
 * not a hole anybody can see, exactly as it is not for a deleted Panel's
 * placement.
 */
export const removeItemFromPanelSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  panelId: z.uuid(),
});
export type RemoveItemFromPanelCommand = z.infer<typeof removeItemFromPanelSchema>;

/**
 * The two things an Item can be besides yours to deal with ("An item is either
 * yours to deal with or finished with", issue 154).
 *
 * **A flag rather than a pair of commands each way**, because both directions
 * are wanted and both have to be idempotent: undoing is the same command with
 * the flag turned round, so nothing has to remember which of a `mark_done` and
 * a `reopen` inverts the other.
 */
export const setDoneSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  done: z.boolean(),
});
export type SetDoneCommand = z.infer<typeof setDoneSchema>;

export const setDismissedSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  dismissed: z.boolean(),
});
export type SetDismissedCommand = z.infer<typeof setDismissedSchema>;

export const associateSchema = commandEnvelopeSchema.extend({
  associationId: z.uuid(),
  itemId: z.uuid(),
  kind: associationKindSchema,
  label: z.string().min(1),
  /** true removes the association instead of adding it. */
  remove: z.boolean().optional(),
});
export type AssociateCommand = z.infer<typeof associateSchema>;

export const setNextActionSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  nextAction: z.string(),
});
export type SetNextActionCommand = z.infer<typeof setNextActionSchema>;

export const setPrioritySchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  priority: prioritySchema.nullable(),
});
export type SetPriorityCommand = z.infer<typeof setPrioritySchema>;

/**
 * set_title / set_description — the two texts the Item's form edits ("Edit an
 * item's title and description on a form of its own", issue 159).
 *
 * **Two commands rather than one save**, because they are two fields resolved
 * last-write-wins independently: the form sends only what changed, so leaving
 * the title alone cannot carry a stale copy of it over an edit made on another
 * device. One `update_item` carrying both would do exactly that.
 *
 * A null description is one that has been cleared, which is the same thing as
 * never having had one - there is no third state, and nothing distinguishes an
 * Item whose description was emptied from one that never got a word.
 */
export const setTitleSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  title: itemTitleSchema,
});
export type SetTitleCommand = z.infer<typeof setTitleSchema>;

export const setDescriptionSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  description: itemDescriptionSchema.nullable(),
});
export type SetDescriptionCommand = z.infer<typeof setDescriptionSchema>;

/**
 * The command registry: name → payload schema. The API mounts one POST route
 * per entry; the client gets a typed sender per entry. Adding a command means
 * adding it here and writing its domain handler; no other wiring.
 */
export const commandSchemas = {
  create_workspace: createWorkspaceSchema,
  rename_workspace: renameWorkspaceSchema,
  delete_workspace: deleteWorkspaceSchema,
  reorder_workspaces: reorderWorkspacesSchema,
  set_workspace_theme: setWorkspaceThemeSchema,
  add_dashboard: addDashboardSchema,
  rename_dashboard: renameDashboardSchema,
  delete_dashboard: deleteDashboardSchema,
  add_panel: addPanelSchema,
  rename_panel: renamePanelSchema,
  delete_panel: deletePanelSchema,
  save_layout: saveLayoutSchema,
  delete_layout: deleteLayoutSchema,
  capture_item: captureItemSchema,
  create_item_type: createItemTypeSchema,
  rename_item_type: renameItemTypeSchema,
  set_item_type_color: setItemTypeColorSchema,
  delete_item_type: deleteItemTypeSchema,
  reorder_item_types: reorderItemTypesSchema,
  move_item_to_panel: moveItemToPanelSchema,
  add_item_to_panel: addItemToPanelSchema,
  remove_item_from_panel: removeItemFromPanelSchema,
  set_done: setDoneSchema,
  set_dismissed: setDismissedSchema,
  associate: associateSchema,
  set_next_action: setNextActionSchema,
  set_priority: setPrioritySchema,
  set_title: setTitleSchema,
  set_description: setDescriptionSchema,
} as const;

export type CommandName = keyof typeof commandSchemas;
export type CommandPayload<N extends CommandName> = z.infer<(typeof commandSchemas)[N]>;

/** What every command endpoint returns. `applied: false` = idempotent replay. */
export const commandResultSchema = z.object({
  ok: z.literal(true),
  applied: z.boolean(),
});
export type CommandResult = z.infer<typeof commandResultSchema>;
