import { z } from 'zod';
import {
  associationKindSchema,
  dashboardNameSchema,
  focusHorizonSchema,
  itemStatusSchema,
  prioritySchema,
  workspaceNameSchema,
} from './domain/item.js';
import { hexColorSchema } from './domain/workspace-themes.js';

/**
 * Mutations are commands, not object PUTs (architecture §4.3).
 * Every command carries a client-generated command ID (idempotent retries)
 * and the client timestamp (last-write-wins conflict resolution).
 */
export const commandEnvelopeSchema = z.object({
  commandId: z.uuid(),
  /** Client wall-clock time when the command was issued. */
  issuedAt: z.iso.datetime(),
  workspaceId: z.string(),
});

/**
 * create_workspace — the envelope's `workspaceId` *is* the new workspace's id,
 * generated by the client like every other user-created id (architecture,
 * "Schema conventions"). That also means the change announces itself on the
 * new workspace without any special casing.
 *
 * No color: it is a function of the colors every other workspace already has,
 * and the client's copy of that list can be stale, so the server picks it.
 */
export const createWorkspaceSchema = commandEnvelopeSchema.extend({
  workspaceId: z.uuid(),
  name: workspaceNameSchema,
});
export type CreateWorkspaceCommand = z.infer<typeof createWorkspaceSchema>;

/**
 * rename_workspace — the envelope's `workspaceId` is the workspace being
 * renamed, so the change announces itself on it like every other change.
 *
 * Deliberately `workspaceNameSchema`, the same one create uses: renaming obeys
 * exactly the rules creating does, and sharing the schema is what stops the two
 * drifting apart. It trims before it measures, so the name is cleaned before
 * uniqueness is decided on it rather than after.
 *
 * Unlike create, the id here names something that already exists, and the
 * workspaces seeded before ids were client-generated are not UUIDs - so the
 * envelope's plain string is what this takes.
 */
export const renameWorkspaceSchema = commandEnvelopeSchema.extend({
  name: workspaceNameSchema,
});
export type RenameWorkspaceCommand = z.infer<typeof renameWorkspaceSchema>;

/**
 * delete_workspace — the envelope on its own: which workspace is the only
 * thing there is to say. Its items are left where they are (architecture,
 * "Schema conventions": tombstones, not deletes), because the router learns
 * from the whole history of where things were filed.
 */
export const deleteWorkspaceSchema = commandEnvelopeSchema;
export type DeleteWorkspaceCommand = z.infer<typeof deleteWorkspaceSchema>;

/**
 * reorder_workspaces — the whole order, not the move that produced it.
 *
 * **The payload is every live workspace in the order they should be in.** A
 * "move this one before that one" would be smaller, and it is the wrong unit
 * for two reasons. Commands carry the client's clock and are resolved
 * last-write-wins (architecture, "Mutations are commands, not object PUTs"), and
 * a whole order is a value that rule can be applied to while a relative move is
 * not - two moves arriving out of turn compose into an order nobody asked for.
 * And it makes the staleness visible: a list that no longer names the same
 * workspaces the account has is refused, where a relative move would quietly
 * succeed against a list the person was not looking at.
 *
 * The envelope's `workspaceId` is the one that was moved. It is not redundant
 * with the list: it is what the change announces itself on, and it is what the
 * audit trail reads as afterwards - "the whole order changed" says nothing
 * about what somebody did.
 *
 * The ids are the envelope's plain strings, not uuids, for the reason renaming
 * takes one: they name workspaces that already exist, and the ones an account
 * starts with predate client-generated ids.
 */
export const reorderWorkspacesSchema = commandEnvelopeSchema
  .extend({
    workspaceIds: z.array(z.string().min(1)).min(1),
  })
  /**
   * A list naming the same workspace twice has no order in it - two positions
   * for one workspace, and one of the account's workspaces necessarily left
   * out. Refused as a shape rather than checked against the database, because
   * it is wrong on its own terms whatever the account holds.
   */
  .refine((cmd) => new Set(cmd.workspaceIds).size === cmd.workspaceIds.length, {
    message: 'a workspace can only be in one place in the order',
    path: ['workspaceIds'],
  })
  /**
   * The workspace that moved has to be one of the workspaces being ordered.
   * Same reason: an order that does not contain the thing it claims to have
   * moved is not a smaller change, it is an inconsistent one.
   */
  .refine((cmd) => cmd.workspaceIds.includes(cmd.workspaceId), {
    message: 'the workspace that moved is not in the order',
    path: ['workspaceIds'],
  });
export type ReorderWorkspacesCommand = z.infer<typeof reorderWorkspacesSchema>;

/**
 * set_workspace_theme — the four colors, not the name of the theme they came
 * from, because four colors is what a workspace stores. The server still
 * refuses a set that is not one of the palette's, which is what keeps "picked
 * from designed options" true rather than merely intended; the day mixing your
 * own is wanted, that check relaxes and nothing else moves.
 */
export const setWorkspaceThemeSchema = commandEnvelopeSchema.extend({
  color: hexColorSchema,
  bar: hexColorSchema,
  ground: hexColorSchema,
  header: hexColorSchema,
});
export type SetWorkspaceThemeCommand = z.infer<typeof setWorkspaceThemeSchema>;

/**
 * add_dashboard — the envelope's `workspaceId` is the workspace it goes in, so
 * the change announces itself on that workspace like every other, and
 * `dashboardId` is the new dashboard's id, generated by the client like every
 * other user-created id (architecture, "Schema conventions").
 *
 * The name obeys the rules a workspace name obeys, by carrying the same
 * schema. Uniqueness is not a shape: it is decided by the handler and the index
 * behind it, in the scope of the workspace rather than the account, so two
 * workspaces may each have a Research ("Add and switch dashboards", issue 32).
 */
export const addDashboardSchema = commandEnvelopeSchema.extend({
  dashboardId: z.uuid(),
  name: dashboardNameSchema,
});
export type AddDashboardCommand = z.infer<typeof addDashboardSchema>;

/**
 * rename_dashboard — which dashboard, and what it is now called. The name obeys
 * exactly the rules adding one does, by carrying the same schema; uniqueness is
 * decided by the handler and the index behind it, in the scope of the workspace
 * ("Rename and delete a dashboard from a dashboard settings page", issue 90).
 *
 * `dashboardId` is the envelope's plain string rather than a uuid, for the
 * reason renaming a workspace takes one: it names something that already
 * exists, and the dashboard every workspace was given when dashboards landed
 * has an id derived from its workspace's, which is not a uuid.
 */
export const renameDashboardSchema = commandEnvelopeSchema.extend({
  dashboardId: z.string(),
  name: dashboardNameSchema,
});
export type RenameDashboardCommand = z.infer<typeof renameDashboardSchema>;

/**
 * delete_dashboard — which dashboard. Its panels go with it once there are
 * panels to go; the actions they showed are keyed to the workspace and are
 * untouched, so nothing written down is lost by removing a place it was shown.
 */
export const deleteDashboardSchema = commandEnvelopeSchema.extend({
  dashboardId: z.string(),
});
export type DeleteDashboardCommand = z.infer<typeof deleteDashboardSchema>;

/** capture_item — the one command with many front doors (architecture §6.5). */
export const captureItemSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  title: z.string().min(1),
  body: z.string().optional(),
  nextAction: z.string().optional(),
});
export type CaptureItemCommand = z.infer<typeof captureItemSchema>;

export const setStatusSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  status: itemStatusSchema,
});
export type SetStatusCommand = z.infer<typeof setStatusSchema>;

export const snoozeUntilSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  until: z.iso.datetime(),
});
export type SnoozeUntilCommand = z.infer<typeof snoozeUntilSchema>;

export const associateSchema = commandEnvelopeSchema.extend({
  associationId: z.uuid(),
  itemId: z.uuid(),
  kind: associationKindSchema,
  label: z.string().min(1),
  /** true removes the association instead of adding it. */
  remove: z.boolean().optional(),
});
export type AssociateCommand = z.infer<typeof associateSchema>;

export const setFocusSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  horizon: focusHorizonSchema.nullable(),
});
export type SetFocusCommand = z.infer<typeof setFocusSchema>;

export const setNextActionSchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  nextAction: z.string(),
});
export type SetNextActionCommand = z.infer<typeof setNextActionSchema>;

export const setPrioritySchema = commandEnvelopeSchema.extend({
  itemId: z.uuid(),
  priority: prioritySchema.nullable(),
});
export type SetPriorityCommand = z.infer<typeof setPrioritySchema>;

/**
 * The command registry: name → payload schema. The API mounts one POST route
 * per entry; the client gets a typed sender per entry. Adding a command means
 * adding it here and writing its domain handler; no other wiring.
 */
export const commandSchemas = {
  create_workspace: createWorkspaceSchema,
  rename_workspace: renameWorkspaceSchema,
  delete_workspace: deleteWorkspaceSchema,
  reorder_workspaces: reorderWorkspacesSchema,
  set_workspace_theme: setWorkspaceThemeSchema,
  add_dashboard: addDashboardSchema,
  rename_dashboard: renameDashboardSchema,
  delete_dashboard: deleteDashboardSchema,
  capture_item: captureItemSchema,
  set_status: setStatusSchema,
  snooze_until: snoozeUntilSchema,
  associate: associateSchema,
  set_focus: setFocusSchema,
  set_next_action: setNextActionSchema,
  set_priority: setPrioritySchema,
} as const;

export type CommandName = keyof typeof commandSchemas;
export type CommandPayload<N extends CommandName> = z.infer<(typeof commandSchemas)[N]>;

/** What every command endpoint returns. `applied: false` = idempotent replay. */
export const commandResultSchema = z.object({
  ok: z.literal(true),
  applied: z.boolean(),
});
export type CommandResult = z.infer<typeof commandResultSchema>;
