import { beforeEach, describe, expect, inject, it } from 'vitest';
import { env, applyD1Migrations } from 'cloudflare:test';

/**
 * Integration level, and deliberately not through `SELF.fetch`: the register
 * has no write path in the application at all - an account is put there by the
 * bootstrap seed, by hand, or one day by onboarding - so there is no interface
 * to enter through. D1 is this service's real infrastructure and this is what
 * entering it directly looks like.
 *
 * Everything an account's data is held to now lives with that data, in
 * tests/integration/accounts/constraints.test.ts. What is left here is the
 * register's own - which accounts exist, who the people are, and which
 * sign-ins are current - and it is still generated by drizzle-kit, which is why
 * the STRICT guard has to stay: the keyword is added to each migration by hand
 * and a regenerated one would silently drop it.
 */

const AT = '2026-08-12T10:00:00.000Z';

beforeEach(async () => {
  await applyD1Migrations(env.DB, inject('migrations'));
  // Every case writes the same account, so without emptying the register first
  // the second would be refused for having a duplicate id rather than for the
  // reason it is about - and would pass while proving nothing. Children before
  // parents, because the foreign keys between the three are real.
  await env.DB.prepare('DELETE FROM sessions').run();
  await env.DB.prepare('DELETE FROM users').run();
  await env.DB.prepare('DELETE FROM tenants').run();
});

describe('Accounts', () => {
  describe('the register holds only what an account can be', () => {
    it('stores an account', async () => {
      await expect(
        env.DB.prepare('INSERT INTO tenants (id, name, created_at) VALUES (?, ?, ?)')
          .bind('another-account', 'Someone', AT)
          .run(),
      ).resolves.toBeTruthy();
    });

    it('refuses a value it would have to reshape to store', async () => {
      // No CHECK covers `name`, so STRICT is the only thing that can refuse
      // this - which is what makes it the case that fails if STRICT is lost.
      await expect(
        env.DB.prepare(
          "INSERT INTO tenants (id, name, created_at) VALUES (?, x'deadbeef', ?)",
        )
          .bind('another-account', AT)
          .run(),
      ).rejects.toThrow();
    });

    it('refuses a joining time that is not a moment', async () => {
      await expect(
        env.DB.prepare('INSERT INTO tenants (id, name, created_at) VALUES (?, ?, ?)')
          .bind('another-account', 'Someone', 'yesterday')
          .run(),
      ).rejects.toThrow();
    });
  });

  /**
   * This is what makes an account that is not in the register unreachable from
   * the application at all, which is why the case that used to arrange one -
   * over in tests/integration/accounts/store.test.ts - is gone. A request now
   * resolves the account of whoever signed in, and there is no user whose
   * account the register does not hold.
   */
  describe('an account always belongs to someone, and a person always to an account in the register', () => {
    beforeEach(async () => {
      await env.DB.prepare('INSERT INTO tenants (id, name, created_at) VALUES (?, ?, ?)')
        .bind('another-account', 'Someone', AT)
        .run();
    });

    it('stores a person against an account there is', async () => {
      await expect(
        env.DB.prepare(
          'INSERT INTO users (id, name, account_id, role, created_at) VALUES (?, ?, ?, ?, ?)',
        )
          .bind('user-someone', 'Someone', 'another-account', 'user', AT)
          .run(),
      ).resolves.toBeTruthy();
    });

    it('refuses a person whose account is in no register', async () => {
      await expect(
        env.DB.prepare(
          'INSERT INTO users (id, name, account_id, role, created_at) VALUES (?, ?, ?, ?, ?)',
        )
          .bind('user-nowhere', 'Nobody', 'no-such-account', 'user', AT)
          .run(),
      ).rejects.toThrow();
    });

    it('refuses a standing that is not one of the two there are', async () => {
      await expect(
        env.DB.prepare(
          'INSERT INTO users (id, name, account_id, role, created_at) VALUES (?, ?, ?, ?, ?)',
        )
          .bind('user-wizard', 'Someone', 'another-account', 'wizard', AT)
          .run(),
      ).rejects.toThrow();
    });
  });
});

describe('Sign-in', () => {
  describe('a sign-in belongs to a person and ends at a stated moment', () => {
    beforeEach(async () => {
      await env.DB.batch([
        env.DB.prepare('INSERT INTO tenants (id, name, created_at) VALUES (?, ?, ?)').bind(
          'another-account',
          'Someone',
          AT,
        ),
        env.DB.prepare(
          'INSERT INTO users (id, name, account_id, role, created_at) VALUES (?, ?, ?, ?, ?)',
        ).bind('user-someone', 'Someone', 'another-account', 'user', AT),
      ]);
    });

    it('refuses a sign-in for somebody who is not a person here', async () => {
      await expect(
        env.DB.prepare(
          'INSERT INTO sessions (id, user_id, created_at, expires_at) VALUES (?, ?, ?, ?)',
        )
          .bind('a-session', 'user-nobody', AT, AT)
          .run(),
      ).rejects.toThrow();
    });

    it('refuses an ending that is not a moment', async () => {
      await expect(
        env.DB.prepare(
          'INSERT INTO sessions (id, user_id, created_at, expires_at) VALUES (?, ?, ?, ?)',
        )
          .bind('a-session', 'user-someone', AT, 'in a while')
          .run(),
      ).rejects.toThrow();
    });
  });

  /**
   * Nothing reads either column yet ("Record the Google account each user signs
   * in with", issue 195), so the database is the whole of this rule: the
   * sign-in that will read them is "Sign in with Google, and retire the list of
   * names" (issue 196), and until it lands there is no
   * interface through which any of these could be attempted.
   */
  describe('the register records who somebody is at Google', () => {
    beforeEach(async () => {
      await env.DB.batch([
        env.DB.prepare('INSERT INTO tenants (id, name, created_at) VALUES (?, ?, ?)').bind(
          'another-account',
          'Someone',
          AT,
        ),
        env.DB.prepare(
          'INSERT INTO users (id, name, account_id, role, email, google_subject, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)',
        ).bind(
          'user-someone',
          'Someone',
          'another-account',
          'user',
          'someone@example.com',
          'google-someone',
          AT,
        ),
      ]);
    });

    it('refuses a second person the same address', async () => {
      await expect(
        env.DB.prepare(
          'INSERT INTO users (id, name, account_id, role, email, created_at) VALUES (?, ?, ?, ?, ?, ?)',
        )
          .bind('user-impostor', 'Impostor', 'another-account', 'user', 'someone@example.com', AT)
          .run(),
      ).rejects.toThrow();
    });

    it('refuses a second person the same Google account', async () => {
      await expect(
        env.DB.prepare(
          'INSERT INTO users (id, name, account_id, role, email, google_subject, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)',
        )
          .bind(
            'user-impostor',
            'Impostor',
            'another-account',
            'user',
            'impostor@example.com',
            'google-someone',
            AT,
          )
          .run(),
      ).rejects.toThrow();
    });

    /**
     * The case the unique indexes could easily have broken: a person's Google
     * account is learned when they first sign in, so everybody starts without
     * one, and an index that counted two absences as a clash would stop a
     * second person ever being added.
     */
    it('lets any number of people be waiting for one', async () => {
      await expect(
        env.DB.batch([
          env.DB.prepare(
            'INSERT INTO users (id, name, account_id, role, created_at) VALUES (?, ?, ?, ?, ?)',
          ).bind('user-anna', 'Anna', 'another-account', 'user', AT),
          env.DB.prepare(
            'INSERT INTO users (id, name, account_id, role, created_at) VALUES (?, ?, ?, ?, ?)',
          ).bind('user-bram', 'Bram', 'another-account', 'user', AT),
        ]),
      ).resolves.toBeTruthy();
    });
  });
});
