import { beforeEach, describe, expect, inject, it } from 'vitest';
import { env, applyD1Migrations } from 'cloudflare:test';

/**
 * Integration level, and deliberately not through `SELF.fetch`: the register
 * has no write path in the application at all - an account is put there by the
 * bootstrap seed, by hand, or one day by onboarding - so there is no interface
 * to enter through. D1 is this service's real infrastructure and this is what
 * entering it directly looks like.
 *
 * Everything an account's data is held to now lives with that data, in
 * tests/integration/accounts/constraints.test.ts. What is left here is the
 * register's own, and it is still generated by drizzle-kit, which is why the
 * STRICT guard has to stay: the keyword is added to each migration by hand and
 * a regenerated one would silently drop it.
 */

const AT = '2026-08-12T10:00:00.000Z';

beforeEach(async () => {
  await applyD1Migrations(env.DB, inject('migrations'));
  // Every case writes the same account, so without emptying the register first
  // the second would be refused for having a duplicate id rather than for the
  // reason it is about - and would pass while proving nothing.
  await env.DB.prepare('DELETE FROM tenants').run();
});

describe('Accounts', () => {
  describe('the register holds only what an account can be', () => {
    it('stores an account', async () => {
      await expect(
        env.DB.prepare('INSERT INTO tenants (id, name, created_at) VALUES (?, ?, ?)')
          .bind('another-account', 'Someone', AT)
          .run(),
      ).resolves.toBeTruthy();
    });

    it('refuses a value it would have to reshape to store', async () => {
      // No CHECK covers `name`, so STRICT is the only thing that can refuse
      // this - which is what makes it the case that fails if STRICT is lost.
      await expect(
        env.DB.prepare(
          "INSERT INTO tenants (id, name, created_at) VALUES (?, x'deadbeef', ?)",
        )
          .bind('another-account', AT)
          .run(),
      ).rejects.toThrow();
    });

    it('refuses a joining time that is not a moment', async () => {
      await expect(
        env.DB.prepare('INSERT INTO tenants (id, name, created_at) VALUES (?, ?, ?)')
          .bind('another-account', 'Someone', 'yesterday')
          .run(),
      ).rejects.toThrow();
    });
  });
});
