/**
 * The renderer: the model in, a single self-contained HTML file out. Imports
 * nothing from the reading side. One file that opens from disk: the styles
 * are inline, there is no script, and the only addresses in it are links a
 * reader follows.
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { renderDiagram } from './diagram.js';

const here = path.dirname(fileURLToPath(import.meta.url));

const esc = (value) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const plural = (count, one, many = `${one}s`) => `${count} ${count === 1 ? one : many}`;

const day = (iso) => iso.slice(0, 10);

/**
 * @param {ReturnType<import('../model.js').buildModel>} model
 * @param {{ explorerHref?: string, stabilityHref?: string, leadTimeHref?: string, selectionHref?: string }} [options]
 * @returns {string} a complete HTML document
 */
export function renderHtml(model, { explorerHref = '../', stabilityHref = '../stability/', leadTimeHref = '../lead-time/', selectionHref = '../selection/' } = {}) {
  const styles = readFileSync(path.join(here, 'styles.css'), 'utf8');
  const { commit, date, repo } = model.drawnFrom;
  const commitCell = !commit
    ? '<span>commit <b>not known</b></span>'
    : repo
      ? `<span>commit <a href="${esc(`https://github.com/${repo}/commit/${commit}`)}" target="_blank" rel="noopener"><b>${esc(commit.slice(0, 7))}</b></a></span>`
      : `<span>commit <b>${esc(commit.slice(0, 7))}</b></span>`;
  const { environments, workflows } = model.deployment;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cockpit Architecture</title>
<style>${styles}</style>
</head>
<body>
<div class="wrap">

  <header class="masthead">
    <p class="eyebrow">Cockpit &middot; architecture</p>
    <h1>Deployment</h1>
    <p class="standfirst">
      Where Cockpit runs: each environment the Worker config declares with every resource it binds, and each
      workflow with what starts it and which environment it deploys. Drawn from the repository alone.
    </p>
    <div class="runmeta">
      ${commitCell}
      <span>commit dated <b>${date ? esc(day(date)) : 'not known'}</b></span>
      <span>${plural(environments.length, 'environment')}</span>
      <span>${plural(workflows.length, 'workflow')}</span>
      <span><a href="${esc(explorerHref)}"><b>Test explorer &rarr;</b></a></span>
      <span><a href="${esc(stabilityHref)}"><b>CI stability &rarr;</b></a></span>
      <span><a href="${esc(leadTimeHref)}"><b>Lead time &rarr;</b></a></span>
      <span><a href="${esc(selectionHref)}"><b>Selection &rarr;</b></a></span>
    </div>
  </header>

  <h2>Where it runs</h2>
  <p class="sectionnote">Highlighted workflows deploy; the arrow goes to the environment they deploy. Each environment lists what it binds, under its own names; <em>inherited</em> marks a setting taken from the top of the Worker config.</p>
  <div class="diagram">
    ${renderDiagram(model)}
  </div>

  <footer>
    Generated by <code>tools/architecture</code> from <code>apps/api/wrangler.jsonc</code> and <code>.github/workflows/</code>.
    The model is published beside this page as <a href="model.json">model.json</a>.
  </footer>

</div>
</body>
</html>
`;
}
