/**
 * The renderer: Model in, a single self-contained HTML file out. Imports
 * model.js and nothing else — never analyze/ (docs/test-explorer-spec.md §6.1).
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { COLUMNS, summarise } from '../model.js';

const here = path.dirname(fileURLToPath(import.meta.url));

const COLUMN_LABEL = { backend: 'Backend', frontend: 'Frontend', browser: 'Browser', contract: 'Contract' };

/**
 * @param {import('../model.js').Model} model
 * @returns {string} a complete HTML document
 */
export function renderHtml(model) {
  const styles = readFileSync(path.join(here, 'styles.css'), 'utf8');
  const client = readFileSync(path.join(here, 'client.js'), 'utf8');
  const totals = summarise(model);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cockpit Test Explorer</title>
<style>${styles}</style>
</head>
<body>
<div class="wrap">

  <header class="masthead">
    <p class="eyebrow">Cockpit &middot; generated test model</p>
    <h1>Which parts of the product own which tests</h1>
    <p class="standfirst">
      Rows are feature areas &mdash; the parts a person would name if asked what the app does &mdash; not files
      and not entities. Columns are counts, never percentages &mdash; a count only tells you where to look
      relative to another row. The last two columns are the ones that mean something on their own: a file
      nothing runs, or a branch nothing takes. Select a row for its rules and its gaps.
    </p>
    <div class="runmeta">
      <span>commit <b>${esc(model.commit)}</b></span>
      <span>generated <b>${esc(model.generatedAt.slice(0, 19).replace('T', ' '))}Z</b></span>
      <span>rules <b>${totals.rules}</b></span>
      <span>files nothing runs <b>${totals.filesNothingRuns}</b></span>
      <span>branches nothing takes <b>${model.coverageAvailable ? totals.branchesNothingTakes : 'unknown'}</b></span>
    </div>
  </header>

  ${model.warnings.length ? warningBlock(model.warnings) : ''}
  ${!model.coverageAvailable ? coverageNote() : ''}

  <section>
    <div class="card">
      <div class="explorer">
        <div class="tablewrap">
          <table id="matrix">
            <thead>
              <tr>
                <th>Concept</th>
                ${COLUMNS.map((c) => `<th class="c">${COLUMN_LABEL[c]}</th>`).join('')}
                <th class="c">Files nothing runs</th>
                <th class="c">Branches nothing takes</th>
              </tr>
            </thead>
            <tbody id="rows"></tbody>
          </table>
        </div>
        <aside class="panel card" id="panel" aria-live="polite">
          <div class="p-empty">Select a row.</div>
        </aside>
      </div>
    </div>

    <div class="note">
      <b>No percentages anywhere on this page.</b> A count is only meaningful next to another row's count &mdash;
      Actions has seven backend rules and Dashboards has one, and they are similar in size, so look at Dashboards.
      Counts reward writing more rules, so a well-pruned suite can score lower than a padded one; the table cannot
      tell those apart on its own.
    </div>
  </section>

  <footer>
    Generated by tools/test-explorer from commit ${esc(model.commit)}. Shape and reasoning:
    docs/test-explorer-spec.md and docs/testing-decisions-wip.md.
  </footer>

</div>
<script>window.__MODEL__ = ${jsonScript(model)};</script>
<script>${client}</script>
</body>
</html>
`;
}

function warningBlock(warnings) {
  return `<div class="note warn"><b>Analyzer warnings.</b><ul>${warnings.map((w) => `<li>${esc(w)}</li>`).join('')}</ul></div>`;
}

function coverageNote() {
  return `<div class="note warn">
    <b>No coverage data found.</b> "Branches nothing takes" reads as <code>unknown</code> below, not zero &mdash;
    a missing measurement must never look like a clean one. This needs each package's Vitest config to write
    <code>coverage/coverage-final.json</code> (docs/test-explorer-spec.md &sect;6.3).
  </div>`;
}

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}

// The two JS line-separator characters, built from char codes rather than
// written literally so they can't hide invisibly in the source file.
const LINE_SEP = String.fromCharCode(0x2028);
const PARA_SEP = String.fromCharCode(0x2029);

/**
 * JSON safe to embed in a <script> element: `<` would otherwise let a string in
 * the data close the tag, and the two Unicode line separators are literal line
 * breaks to a JavaScript parser even though JSON.stringify leaves them raw.
 */
function jsonScript(value) {
  return JSON.stringify(value)
    .split('<').join('\\u003c')
    .split(LINE_SEP).join('\\u2028')
    .split(PARA_SEP).join('\\u2029');
}
