/**
 * The renderer: Model in, a single self-contained HTML file out. Imports
 * model.js and nothing else — never analyze/ (docs/test-explorer-spec.md §6.1).
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { LEVELS, summarise } from '../model.js';

const here = path.dirname(fileURLToPath(import.meta.url));

/**
 * @param {import('../model.js').Model} model
 * @param {{ repoRelPrefix: string }} options repoRelPrefix: path from the report's own directory
 *   back to the repo root (e.g. "../../.."), used to build clickable file links — see cli.js.
 * @returns {string} a complete HTML document
 */
export function renderHtml(model, { repoRelPrefix }) {
  const styles = readFileSync(path.join(here, 'styles.css'), 'utf8');
  const client = readFileSync(path.join(here, 'client.js'), 'utf8');
  const totals = summarise(model);

  const payload = {
    levels: LEVELS,
    tree: model.tree,
    availableLevels: model.availableLevels,
    coverageAvailable: model.coverageAvailable,
    commitUrl: model.commitUrl,
    repoRelPrefix,
  };

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cockpit Test Explorer</title>
<style>${styles}</style>
</head>
<body>
<div class="wrap">

  <header class="masthead">
    <p class="eyebrow">Cockpit &middot; generated test model</p>
    <h1>Which parts of the product own which tests</h1>
    <p class="standfirst">
      Rows are feature areas &mdash; the parts a person would name if asked what the app does &mdash; and can
      nest (a big area like Dashboards can have sub-areas of its own). Columns are counts, never
      percentages &mdash; a count only tells you where to look relative to another row.
    </p>
    <div class="runmeta">
      ${
        model.commitUrl
          ? `<span>commit <a href="${esc(model.commitUrl)}" target="_blank" rel="noopener"><b>${esc(model.commit)}</b></a></span>`
          : `<span>commit <b>${esc(model.commit)}</b></span>`
      }
      <span>generated <b>${esc(model.generatedAt.slice(0, 19).replace('T', ' '))}Z</b></span>
      <span>rules <b>${totals.rules}</b></span>
      <span>files nothing runs <b>${totals.filesNothingRuns}</b></span>
      <span>branches nothing takes <b>${model.coverageAvailable ? totals.branchesNothingTakes : 'unknown'}</b></span>
    </div>
  </header>

  ${model.warnings.length ? warningBlock(model.warnings) : ''}
  ${!model.coverageAvailable ? coverageNote() : ''}

  <section class="legend card">
    <p class="legend-title">How to read this</p>
    <div class="legend-grid">
      ${LEVELS.map((l) => `<div class="legend-item"><b>${esc(l.label)}</b> ${esc(l.name)} &mdash; ${esc(l.description)}</div>`).join('')}
    </div>
    <div class="legend-grid">
      <div class="legend-item"><b>Files nothing runs</b> source files this area owns (per concepts.json) that no test file imports at all &mdash; a file with zero tests touching it, at any level.</div>
      <div class="legend-item"><b>Branches nothing takes</b> a specific <code>if</code>/<code>?:</code>/<code>&amp;&amp;</code> branch, in a file this area owns, where real coverage data shows one path was never exercised &mdash; e.g. an <code>if</code> with no <code>else</code>, tested only on the true side. Needs coverage data to be collected first (see the note above if it says "unknown").</div>
    </div>
  </section>

  <section>
    <div class="explorer">
      <div class="card">
        <div class="tablewrap">
          <table id="matrix">
            <thead>
              <tr>
                <th>Concept</th>
                ${LEVELS.map((l) => `<th class="c" title="${esc(l.name)} — ${esc(l.description)}">${esc(l.label)}</th>`).join('')}
                <th class="c" title="Source files this area owns that no test imports">Files nothing runs</th>
                <th class="c" title="Branches in this area's files that real coverage shows are never taken">Branches nothing takes</th>
              </tr>
            </thead>
            <tbody id="rows"></tbody>
          </table>
        </div>
      </div>
      <aside class="panel card" id="panel" aria-live="polite">
        <div class="p-empty">Select a row.</div>
      </aside>
    </div>

    <div class="note">
      <b>No percentages anywhere on this page.</b> A count is only meaningful next to another row's count &mdash;
      Actions has seven backend rules and Dashboards has one, and they are similar in size, so look at Dashboards.
      Counts reward writing more rules, so a well-pruned suite can score lower than a padded one; the table cannot
      tell those apart on its own.
    </div>
  </section>

  <footer>
    Generated by tools/test-explorer${model.commit !== 'unknown' ? ` from commit ${esc(model.commit)}` : ''}. Shape and
    reasoning: docs/test-explorer-spec.md and docs/testing-decisions-wip.md.
  </footer>

</div>
<script>window.__MODEL__ = ${jsonScript(payload)};</script>
<script>${client}</script>
</body>
</html>
`;
}

function warningBlock(warnings) {
  return `<div class="note warn"><b>Analyzer warnings.</b><ul>${warnings.map((w) => `<li>${esc(w)}</li>`).join('')}</ul></div>`;
}

function coverageNote() {
  return `<div class="note warn">
    <b>No coverage data found.</b> "Branches nothing takes" reads as <code>unknown</code> below, not zero &mdash;
    a missing measurement must never look like a clean one. Run <code>pnpm test:coverage</code> first
    (docs/test-explorer-spec.md &sect;6.3).
  </div>`;
}

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}

// The two JS line-separator characters, built from char codes rather than
// written literally so they can't hide invisibly in the source file.
const LINE_SEP = String.fromCharCode(0x2028);
const PARA_SEP = String.fromCharCode(0x2029);

/**
 * JSON safe to embed in a <script> element: `<` would otherwise let a string in
 * the data close the tag, and the two Unicode line separators are literal line
 * breaks to a JavaScript parser even though JSON.stringify leaves them raw.
 */
function jsonScript(value) {
  return JSON.stringify(value)
    .split('<').join('\\u003c')
    .split(LINE_SEP).join('\\u2028')
    .split(PARA_SEP).join('\\u2029');
}
